baseURL = "https://inclusivenaming.org"
title = "Inclusive Naming Initiative"
disableKinds = ["taxonomy", "taxonomyTerm"]
copyright = "The Inclusive Naming Initiative authors and collaborating organizations"
enableGitInfo = true
summaryLength = 20

[mediaTypes]
  [mediaTypes.'text/html']
    suffixes = ['custom']

[outputFormats]
  [outputFormats.custom]
    mediaType = 'text/html'

[markup.highlight]
style = "paraiso-dark"

[blackfriday]
extensions = ["hardLineBreak"]

[params]
font_awesome_version = "5.12.0"
description = "Helping projects and companies make consistent, responsible choices to remove harmful language"
favicon = "favicon.png"
repositoryUrl = "https://github.com/inclusivenaming"
contentDir = "/content/"
[params.logos]
navbar = "inclusive-naming-logo.svg"

[[params.social]]
name = "Twitter"
url = "https://twitter.com/inclusivenaming"
icon = "fab fa-twitter"

[[params.social]]
name = "YouTube"
url = "https://www.youtube.com/channel/UCP1oEIxHSl77RCWRPwRjdiQ"
icon = "fab fa-youtube"

[[params.social]]
name = "GitHub"
url = "https://github.com/inclusivenaming"
icon = "fab fa-github"

[[params.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/company/inclusive-naming/"
icon = "fab fa-linkedin-in"

[[params.social]]
name = "Mailing list"
url = "https://groups.google.com/g/inclusivenaming"
icon = "fas fa-envelope"

[[params.social]]
name = "Slack Invite"
url = "https://communityinviter.com/apps/inclusive-naming/invite"
icon = "fab fa-slack"

[[params.fonts]]
name = "Cairo"
sizes = [300, 400, 600, 700, 900]
type = "sans_serif"

[[params.fonts]]
name = "Lexend Deca"
sizes = [400]
type = "heading_font"

[[menu.main]]
name = "About"
url = "#"
weight = 1
identifier ="about"

[[menu.main]]
name = "About the initiative"
url = "/about"
parent = "about"
weight = 1

[[menu.main]]
name = "Project leadership"
url = "/leadership"
parent = "about"
weight = 2

[[menu.main]]
name = "Get involved"
url = "#"
weight = 3
identifier = "getinvolved"

[[menu.main]]
name = "Participate"
url = "/participate"
parent = "getinvolved"
weight = 1

[[menu.main]]
name = "Sponsor"
url = "/sponsor"
parent="getinvolved"
weight = 2

[[menu.main]]
name = "Workstreams"
url = "/workstreams"
parent = "getinvolved"
weight = 2

[[menu.main]]
name = "Meeting calendar"
url = "/calendar"
parent = "getinvolved"
weight = 3

[[menu.main]]
name = "Code of conduct"
url = "/code-of-conduct"
parent = "getinvolved"
weight = 4

[[menu.main]]
name = "Word lists"
url = "#"
identifier = "lists"
weight = 5

[[menu.main]]
name = "Overview"
url = "/word-lists"
parent = "lists"
weight = 1

[[menu.main]]
name = "Tier 1: Replace Immediately"
url = "/word-lists/tier-1"
parent = "lists"
weight = 2

[[menu.main]]
name = "Tier 2: Strongly Consider Replacing"
url = "/word-lists/tier-2"
parent = "lists"
weight = 3

[[menu.main]]
name = "Tier 3: Recommendations to Replace"
url = "/word-lists/tier-3"
parent = "lists"
weight = 4

[[menu.main]]
name = "No Changes Recommended"
url = "/word-lists/no-change"
parent = "lists"
weight = 5

[[menu.main]]
name = "Wordlist Template"
url = "/word-lists/template"
parent = "lists"
weight = 6

[[menu.main]]
name = "Resources"
url = "#"
identifier = "lang"
weight = 6

[[menu.main]]
name ="Language evaluation framework"
url = "/language/evaluation-framework"
parent = "lang"
weight = 2

[[menu.main]]
name = "Implementation path"
url = "/language/implementation-path"
parent = "lang"
weight = 3

[[menu.main]]
name = "Related projects"
url = "/related-projects"
weight = 7

[[menu.main]]
name = "FAQs"
url = "/faqs"
weight = 8

[[menu.main]]
name = "News & Media"
url = "#"
weight = 9
identifier = "news-and-media"

[[menu.main]]
name = "Blog"
url = "/blog"
parent = "news-and-media"
weight = 1

[[menu.main]]
name = "Media mentions"
url = "/media-mentions"
parent = "news-and-media"
identifier = "media-mentions"
weight = 2

[[menu.main]]
name = "Presentations"
url = "https://github.com/inclusivenaming/org/tree/main/ws-marketing"
parent = "news-and-media"
identifier = "presentations"
weight = 3