[build]
publish = "public"
command = "hugo"

[build.environment]
HUGO_VERSION = "0.145.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "16.14.0"

[context.deploy-preview]
command = "hugo"

[context.branch-deploy]
command = "hugo"

[context.production.environment]
HUGO_ENV = "production"
