[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.145.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify"

[context.branch-deploy]
command = "hugo --gc --minify"

[context.production.environment]
HUGO_ENV = "production"
